### ISSUE TITLE
Cannot run npm script inside Firepit

### ISSUE THREAD

**Issue by jsayol** [abehaskins/firepit#4]
If I try running an npm script from inside Firepit I get the following error:
```
C:\Users\josep\Firepit\test\functions>npm run build
npm ERR! path C:\Users\josep\.cache\firebase\cli\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\josep\.cache\firebase\cli\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\josep\AppData\Roaming\npm-cache\_logs\2019-01-24T22_34_39_337Z-debug.log
```

Running it with the "normal" npm works as expected:
```
C:\Users\josep\Firepit\test\functions>npm run build

> functions@ build C:\Users\josep\Firepit\test\functions
> tsc
```
[2019-01-24T22_34_39_337Z-debug.log](https://github.com/abehaskins/firepit/files/2793905/2019-01-24T22_34_39_337Z-debug.log)

**Comment by abeisgoat** [comment]
Ah good catch, this is a known regression which is discussed in [the only TODO in the code](https://github.com/abehaskins/firepit/blob/master/firepit.js#L201). As a workaround you should be able to say `npm run build --prefix .` and I believe it should work.

This issue stems from using a custom prefix (read: cache directory) for NPM to avoid conflicts with global installs. This is fine, but `npm` uses the prefix too aggressively when it's passed as a cli arg, resulting in it's inability to find local package.json because `prefix` overwrites `cwd` even when `-g` is not used.

I'll work on a fix, but it probably wont be up till tomorrow.

**Comment by abeisgoat** [comment]
Should be fixed, hmu if it's still wonky. Thanks for the report.
